package com.sjx.simple.dao;

import com.sjx.simple.entities.SimpleUser;

public interface SimpleUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table simple_user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table simple_user
     *
     * @mbggenerated
     */
    int insert(SimpleUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table simple_user
     *
     * @mbggenerated
     */
    int insertSelective(SimpleUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table simple_user
     *
     * @mbggenerated
     */
    SimpleUser selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table simple_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SimpleUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table simple_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SimpleUser record);
}